import { mutation } from "./_generated/server";
import { v } from "convex/values";

const SEED_UPLOADS = [
  {
    title: "Dawn chorus — Fitzroy Gardens",
    description: "Incredible burst of birdsong just before sunrise",
    lat: -37.8136,
    lon: 144.9806,
    locationLabel: "Fitzroy Gardens, Melbourne",
    dominantClass: "birds",
    biodiversityScore: 82,
    durationSeconds: 47,
    likeCount: 14,
    listenCount: 63,
    tags: ["dawn", "birds", "park"],
  },
  {
    title: "Tram on Collins St",
    description: "City tram grinding past in the afternoon",
    lat: -37.8136,
    lon: 144.9631,
    locationLabel: "Collins St, Melbourne CBD",
    dominantClass: "traffic",
    biodiversityScore: 5,
    durationSeconds: 22,
    likeCount: 3,
    listenCount: 18,
    tags: ["tram", "city", "traffic"],
  },
  {
    title: "Crickets at Royal Botanic Gardens",
    description: "Summer evening insect chorus near the ornamental lake",
    lat: -37.8304,
    lon: 144.9798,
    locationLabel: "Royal Botanic Gardens, Melbourne",
    dominantClass: "insects",
    biodiversityScore: 71,
    durationSeconds: 60,
    likeCount: 22,
    listenCount: 105,
    tags: ["insects", "night", "botanic"],
  },
  {
    title: "Wind through gum trees",
    description: "Strong westerly making the eucalyptus branches sway",
    lat: -37.7963,
    lon: 144.9975,
    locationLabel: "Northcote, Melbourne",
    dominantClass: "wind",
    biodiversityScore: 18,
    durationSeconds: 34,
    likeCount: 7,
    listenCount: 29,
    tags: ["wind", "trees", "gumtrees"],
  },
  {
    title: "Construction site — Docklands",
    description: "Piling and heavy machinery near the waterfront development",
    lat: -37.8155,
    lon: 144.9399,
    locationLabel: "Docklands, Melbourne",
    dominantClass: "construction",
    biodiversityScore: 2,
    durationSeconds: 15,
    likeCount: 1,
    listenCount: 9,
    tags: ["construction", "docklands"],
  },
  {
    title: "Pre-dawn silence — Yarra River bank",
    description: "Almost no sound at 4am — just distant water",
    lat: -37.8226,
    lon: 144.9711,
    locationLabel: "Yarra River, Southbank",
    dominantClass: "silence",
    biodiversityScore: 12,
    durationSeconds: 90,
    likeCount: 31,
    listenCount: 148,
    tags: ["silence", "river", "night"],
  },
  {
    title: "Lorikeet flock — St Kilda Botanical Gardens",
    description: "Rainbow lorikeets going absolutely wild in the fig trees",
    lat: -37.8652,
    lon: 144.9844,
    locationLabel: "St Kilda Botanical Gardens",
    dominantClass: "birds",
    biodiversityScore: 88,
    durationSeconds: 52,
    likeCount: 41,
    listenCount: 210,
    tags: ["lorikeet", "birds", "stkilda"],
  },
  {
    title: "Peak hour — Flinders St Station",
    description: "Morning rush beneath the clocks — full urban soundscape",
    lat: -37.8183,
    lon: 144.9671,
    locationLabel: "Flinders St Station, Melbourne",
    dominantClass: "traffic",
    biodiversityScore: 4,
    durationSeconds: 28,
    likeCount: 9,
    listenCount: 44,
    tags: ["station", "rush", "urban"],
  },
  {
    title: "Cicadas at Merri Creek Trail",
    description: "Dense cicada hum on a hot January afternoon",
    lat: -37.7614,
    lon: 144.9996,
    locationLabel: "Merri Creek Trail, Coburg",
    dominantClass: "insects",
    biodiversityScore: 66,
    durationSeconds: 41,
    likeCount: 18,
    listenCount: 87,
    tags: ["cicadas", "creek", "summer"],
  },
  {
    title: "Ocean wind — Point Lonsdale",
    description: "Bass Strait gale rolling in — almost nothing else",
    lat: -38.2775,
    lon: 144.6156,
    locationLabel: "Point Lonsdale, Bellarine Peninsula",
    dominantClass: "wind",
    biodiversityScore: 24,
    durationSeconds: 55,
    likeCount: 12,
    listenCount: 51,
    tags: ["ocean", "wind", "coast"],
  },
  {
    title: "Kookaburra at dawn — Dandenong Ranges",
    description: "A pair calling across the gully in the misty morning",
    lat: -37.8761,
    lon: 145.3543,
    locationLabel: "Dandenong Ranges National Park",
    dominantClass: "birds",
    biodiversityScore: 91,
    durationSeconds: 38,
    likeCount: 55,
    listenCount: 273,
    tags: ["kookaburra", "rainforest", "dawn"],
  },
  {
    title: "Roadworks — Hoddle St",
    description: "Night resurfacing crew — jackhammer and roller",
    lat: -37.8068,
    lon: 144.9882,
    locationLabel: "Hoddle St, Clifton Hill",
    dominantClass: "construction",
    biodiversityScore: 1,
    durationSeconds: 20,
    likeCount: 0,
    listenCount: 7,
    tags: ["roadworks", "night"],
  },
  {
    title: "Evening silence — Prahran Market alley",
    description: "Market closed, alley empty — just distant TV through a window",
    lat: -37.8491,
    lon: 144.9929,
    locationLabel: "Prahran Market, South Yarra",
    dominantClass: "silence",
    biodiversityScore: 8,
    durationSeconds: 62,
    likeCount: 6,
    listenCount: 22,
    tags: ["silence", "market", "evening"],
  },
  {
    title: "Frogs after rain — Westgate Park",
    description: "Chorus frogs erupted 20 min after the storm",
    lat: -37.8354,
    lon: 144.9295,
    locationLabel: "Westgate Park, Port Melbourne",
    dominantClass: "insects",
    biodiversityScore: 79,
    durationSeconds: 70,
    likeCount: 38,
    listenCount: 189,
    tags: ["frogs", "rain", "wetland"],
  },
  {
    title: "Magpies — Carlton Gardens",
    description: "Territorial warbling during spring — three birds, overlapping",
    lat: -37.8063,
    lon: 144.9726,
    locationLabel: "Carlton Gardens, Melbourne",
    dominantClass: "birds",
    biodiversityScore: 77,
    durationSeconds: 44,
    likeCount: 27,
    listenCount: 133,
    tags: ["magpie", "spring", "warbling"],
  },
];

export const seedTestUploads = mutation({
  args: { userId: v.string() },
  returns: v.number(),
  handler: async (ctx, args) => {
    let count = 0;
    // Spread creation times over the past 30 days
    const now = Date.now();
    const thirtyDays = 30 * 24 * 60 * 60 * 1000;

    for (let i = 0; i < SEED_UPLOADS.length; i++) {
      const seed = SEED_UPLOADS[i];
      // Stagger timestamps so they appear as different entries
      const createdAt = now - Math.floor((i / SEED_UPLOADS.length) * thirtyDays);

      await ctx.db.insert("uploads", {
        userId: args.userId,
        title: seed.title,
        description: seed.description,
        lat: seed.lat,
        lon: seed.lon,
        locationLabel: seed.locationLabel,
        dominantClass: seed.dominantClass,
        biodiversityScore: seed.biodiversityScore,
        durationSeconds: seed.durationSeconds,
        likeCount: seed.likeCount,
        listenCount: seed.listenCount,
        tags: seed.tags,
        elasticSynced: false,
      });

      count++;
    }

    return count;
  },
});
